# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.Contact'),
        ),
        migrations.AddField(
            model_name='representation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.Location'),
        ),
        migrations.AddField(
            model_name='representation',
            name='role',
            field=models.CharField(default='Representative', max_length=150),
        ),
    ]
