# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0002_auto_20161214_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.City'),
        ),
        migrations.AddField(
            model_name='template',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.Issue'),
        ),
        migrations.AddField(
            model_name='template',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.State'),
        ),
    ]
