# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0004_auto_20161217_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.State'),
        ),
    ]
