# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0005_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='level',
            field=models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('city', 'City')], default='city', max_length=10),
        ),
    ]
