# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0012_auto_20170128_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ordinal',
            field=models.PositiveIntegerField(default=900000),
        ),
    ]
