# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0014_auto_20170204_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(null=True)),
                ('ordinal', models.PositiveIntegerField(default=900000)),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='sources',
            field=models.ManyToManyField(to='cwc.Source'),
        ),
    ]
