# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 10:29
from __future__ import unicode_literals

import cwc.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0018_auto_20170205_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_group',
            field=models.ForeignKey(default=cwc.models.first_group, on_delete=django.db.models.deletion.CASCADE, to='cwc.IssueGroup'),
        ),
    ]
