# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0019_auto_20170205_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.Contact'),
        ),
    ]
