# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # extracts different roles from contacts
    def create_roles(apps, schema_editor):
        Role = apps.get_model("cwc", "Role")
        Contact = apps.get_model("cwc", "Contact")
        all_contacts = Contact.objects.all()
        for contact in all_contacts:
            try:
                existing_role = Role.objects.get(name=contact.role)
            except Role.DoesNotExist:
                role = Role(name=contact.role)
                role.save()


    dependencies = [
        ('cwc', '0021_role'),
    ]

    operations = [
        migrations.RunPython(create_roles),
        migrations.AddField(
            model_name='template',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cwc.Role'),
        )
    ]
