# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0022_template_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='sources',
            field=models.ManyToManyField(blank=True, to='cwc.Source'),
        ),
    ]
