# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0024_role_do_not_display_in_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
